version: "3.3"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
      - memcache
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_USER: updatejson
      DB_PASS: updatejson
      DB_HOST: database
      DB_DATABASE: widget
      GIN_MODE: release
      DB_MODE: release
      MEMCACHE_SERVERS: "memcache"
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: updatejson
      MYSQL_PASSWORD: updatejson
      MYSQL_DATABASE: widget
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - "dbdata:/var/lib/mysql"
  memcache:
    image: memcached
    restart: always
    command: ["-m", "64m"]

volumes:
  dbdata: