version: "3.3"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      DB_USER: updatejson
      DB_PASS: updatejson
      DB_HOST: database
      DB_DATABASE: widget
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: updatejson
      MYSQL_PASSWORD: updatejson
      MYSQL_DATABASE: widget
      MYSQL_RANDOM_ROOT_PASSWORD: "true"