version: "3.3"
services:
  updatejson:
    image: ghcr.io/cfwidget/updatejson
    restart: always
    depends_on:
      - database
    environment:
      DB_USER: updatejson
      DB_PASS_FILE: "/run/secrets/updatejson_db_pw"
      DB_HOST: database
      DB_DATABASE: widget
      GIN_MODE: release
      DB_MODE: release
      CORE_KEY_FILE: "/run/secrets/core_key"
      CACHE_TTL: 1h
    secrets:
      - core_key
      - updatejson_db_pw
    networks:
      - default
      - ingress_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST}`)"
        - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
        - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=myresolver"
        - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8080"

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: updatejson
      MYSQL_PASSWORD_FILE: "/run/secrets/updatejson_db_pw"
      MYSQL_DATABASE: widget
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    secrets:
      - updatejson_db_pw
    volumes:
      - "dbdata:/var/lib/mysql"

secrets:
  core_key:
    external: true
  updatejson_db_pw:
    external: true

volumes:
  dbdata:

networks:
  ingress_default:
    external: true
